const month = Object.freeze({"январь":1, "февраль":2, "март":3, "апрель":4, "май":5, "июнь":6, "июль":7,
  "август":8, "сентябрь":9, "октябрь":10, "ноябрь":11, "декабрь":12});

let treedata = {
  name: "Направления",
  children: [
  	{
  		name:"Активный отдых",
  		children:[
  			{
        name:"Походы по России", 
        children:[
          {
          name:"Горные походы", 
          children:[
            {
              name:"Хибины",
              visa:false,
              temperature:-20,
              hotel:2000,
              tickets:5000,
              rating: 7.5,
              season:"март"
            },
            {
              name:"Эльбрус",
              visa:false,
              temperature:-25,
              hotel:3000,
              tickets:6000,
              rating: 7,
              season:"июнь"
            },
          ]},
          {
          name:"Водные походы",
          children:[
            {
              name:"Шуя",
              visa:false,
              temperature:10,
              hotel:0,
              tickets:3000,
              rating: 7.5,
              season:"май"
            },
            { 
              name:"р. Катунь",
              visa:false,
              temperature:-25,
              hotel:0,
              tickets:4000,
              rating: 7.5,
              season:"июнь"
            },
            {
              name:"р. Уксанйоки",
              visa:false,
              temperature:8,
              hotel:0,
              tickets:3000,
              rating: 8,
              season:"май"
            },
            {
              name:"р. Мста",
              visa:false,
              temperature:12,
              hotel:0,
              tickets:1000,
              rating: 6.5,
              season:"май"
            },
            {
              name:"р. Кереть",
              visa:false,
              temperature:11,
              hotel:0,
              tickets:800,
              rating: 7,
              season:"июнь"
            },
            {
              name:"р. Тверца",
              visa:false,
              temperature:11,
              hotel:0,
              tickets:800,
              rating: 6,
              season:"май"
            },
            {
              name:"Белое Море",
              visa:false,
              temperature:15,
              hotel:0,
              tickets:3500,
              rating: 9,
              season:"июль"
            },
            {
              name:"Ладожское озеро",
              visa:false,
              temperature:19,
              hotel:0,
              tickets:3000,
              rating: 9,
              season:"август"
            },
          ]},
          {
          name:"Пешие походы",
          children:[
            {name:"Байкал",
        visa:false,
              temperature:16,
              hotel:0,
              tickets:3567,
              rating: 10,
              season:"июль"
          },
            {name:"Камчатка",
        visa:false,
              temperature:32,
              hotel:0,
              tickets:2980,
              rating: 7,
              season:"сентябрь"
          },
            {name:"Алтай",
        visa:false,
              temperature:24,
              hotel:0,
              tickets:1700,
              rating: 7,
              season:"июнь"
          },
            {name:"Ергаки",
        visa:false,
              temperature:18,
              hotel:0,
              tickets:1259,
              rating: 5,
              season:"август"
          },
            {name:"Колвицкие тундры",
        visa:false,
              temperature:5,
              hotel:0,
              tickets:1897,
              rating: 8,
              season:"март"
          },
            {name:"Паанаярви",
        visa:false,
              temperature:25,
              hotel:0,
              tickets:3678,
              rating: 9,
              season:"июль"
          }
          ]},
        ]},
  			{
        name:"Горные лыжи/Сноуборд",
        children:[
            {
            name:"Россия",
            children:[
              {name:"Роза Хутор (Сочи)",
              visa:false,
          temperature:-15,
              hotel:8000,
              tickets:3800,
              rating: 8,
              season:"январь"
          },
              {name:"Бобровый лог (Красноярск)",
              visa:false,
          temperature:-18,
              hotel:9300,
              tickets:2648,
              rating: 6,
              season:"декабрь"
          },
              {name:"Сорочаны (Московская область)",
              visa:false,
          temperature:-20,
              hotel:6950,
              tickets:1780,
              rating: 7,
              season:"январь"
          },
              {name:"Игора (Ленинградская область)",
              visa:false,
          temperature:-30,
              hotel:5600,
              tickets:2987,
              rating: 9,
              season:"ноябрь"
          },
              {name:"Большой Вудъявр (Мурманская область)",
              visa:false,
          temperature:-35,
              hotel:6890,
              tickets:3248,
              rating: 5,
              season:"январь"
          },
              {name:"Домбай (Кавказ)",
              visa:false,
          temperature:-10,
              hotel:10300,
              tickets:4520,
              rating: 10,
              season:"февраль"
          }
            ]},
            {
            name:"Финляндия",
            children:[
              {
                name:"Рука",
                visa:true,
                temperature:-8,
                hotel:15000,
                tickets:13850,
                rating: 10,
                season:"март"
              },
            ]},
            {
            name:"Швеция",
            children:[
              {name:"Оре",
          		visa:true,
                temperature:-12,
                hotel:17560,
                tickets:12500,
                rating: 10,
                season:"февраль"
            },
            ]},
            {
            name:"Франция",
            children:[
              {name:"Шамони",
          		visa:true,
                temperature:7,
                hotel:18500,
                tickets:9560,
                rating: 10,
                season:"январь"
            },
              {name:"Аворья",
          		visa:true,
                temperature:5,
                hotel:17860,
                tickets:9830,
                rating: 9,
                season:"апрель"
            },
              {name:"Ливиньо",
          		visa:true,
                temperature:12,
                hotel:23000,
                tickets:7453,
                rating: 7,
                season:"февраль"
            },
              {name:"Сен-Жерве-ле-Бен",
          		visa:true,
                temperature:-12,
                hotel:17560,
                tickets:5489,
                rating:6,
                season:"март"
            }
            ]},
            {
            name:"Италия",
            children:[
              {name:"Ливиньо",
          		visa:true,
                temperature:15,
                hotel:15750,
                tickets:8762,
                rating:8,
                season:"февраль"
            }
            ]},
            {
            name:"Швейцария",
            children:[
              {name:"Церматт",
          		visa:true,
                temperature:9,
                hotel:11600,
                tickets:10256,
                rating:8,
                season:"март"
            },
              {name:"Санкт-Мориц",
          		visa:true,
                temperature:7,
                hotel:13500,
                tickets:9638,
                rating:9,
                season:"апрель"
            }
            ]}
          ]},
        {
        name:"Трофи",
        children:[
            {
            name:"Россия",
            children:[
              {name:"п-ов Рыбачий",
          		visa:false,
                temperature:8,
                hotel:13500,
                tickets:900,
                rating:4,
                season:"август"
            }
            ]},
          ]},
  	]},
  	{
      name:"Пляжный отдых",
      children:[
          {
          name:"Россия", 
          children:[
            {
            name:"Сочи",
            children:[
              {name:"Сочи",
          		visa:false,
                temperature:32,
                hotel:9860,
                tickets:1650,
                rating:7,
                season:"август"
            },
              {name:"Адлер",
          		visa:false,
                temperature:35,
                hotel:10700,
                tickets:1800,
                rating:8,
                season:"июнь"
            },
              {name:"Дагомыс",
         		 visa:false,
                temperature:29,
                hotel:12300,
                tickets:2350,
                rating:7.5,
                season:"июль"
            },
              {name:"Лазаревское",
          		visa:false,
                temperature:25,
                hotel:8500,
                tickets:2289,
                rating:8,
                season:"июль"
            }
            ]},
            {
            name:"Крым",
            children:[
              {name:"Алушта",
          		visa:false,
                temperature:28,
                hotel:12740,
                tickets:3919,
                rating:8,
                season:"июль"
            },
              {name:"Евпатория",
          		visa:false,
                temperature:30,
                hotel:10250,
                tickets:3454,
                rating:9,
                season:"июнь"
            },
              {name:"Ялта",
          		visa:false,
                temperature:25,
                hotel:11800,
                tickets:3721,
                rating:10,
                season:"август"
            },
              {name:"Гурзуф",
          		visa:false,
                temperature:32,
                hotel:9900,
                tickets:3286,
                rating:7,
                season:"сентябрь"
            },
              {name:"Коктебель",
         		 visa:false,
                temperature:35,
                hotel:11690,
                tickets:3145,
                rating:8,
                season:"июль"
            },
              {name:"Балаклава",
         		visa:false,
                temperature:28,
                hotel:13650,
                tickets:3759,
                rating:6,
                season:"август"
            },
              {name:"Керчь",
          		visa:false,
                temperature:33,
                hotel:12820,
                tickets:3592,
                rating:9,
                season:"июль"
            }
            ]},
            {
            name:"Краснодарский край",
            children:[
              {name:"Анапа",
          		visa:false,
                temperature:25,
                hotel:6520,
                tickets:2589,
                rating:7,
                season:"сентябрь"
            },
              {name:"Ейск",
          		visa:false,
                temperature:22,
                hotel:7200,
                tickets:2663,
                rating:6,
                season:"май"
            },
              {name:"Небуг",
         		visa:false,
                temperature:28,
                hotel:5900,
                tickets:2152,
                rating:8,
                season:"июнь"
            },
              {name:"Лазаревское",
          		visa:false,
                temperature:29,
                hotel:6820,
                tickets:2498,
                rating:5,
                season:"июль"
            },
              {name:"Новороссийск",
          		visa:false,
                temperature:30,
                hotel:5230,
                tickets:1869,
                rating:4,
                season:"август"
            },
              {name:"Геленджик",
          		visa:false,
                temperature:24,
                hotel:4690,
                tickets:3343,
                rating:6,
                season:"июль"
            },
            ]},
          ]},
          {
          name:"Тропические страны",
          children:[
            {
            name:"Мальдивы",
            children:[
              {name:"Южный Мале",
         		visa:true,
                temperature:30,
                hotel:23150,
                tickets:9006,
                rating:10,
                season:"сентябрь"
            },
              {name:"Маафуши",
          		visa:true,
                temperature:34,
                hotel:24420,
                tickets:9421,
                rating:10,
                season:"ноябрь"
            },
              {name:"Атол Ваадху",
          		visa:true,
                temperature:32,
                hotel:25890,
                tickets:10069,
                rating:10,
                season:"октябрь"
            },
              {name:"Атолл Ари",
          		visa:true,
                temperature:36,
                hotel:22220,
                tickets:10637,
                rating:10,
                season:"сентябрь"
            },
              {name:"Атолл Лавиани",
          		visa:true,
                temperature:35,
                hotel:21730,
                tickets:9859,
                rating:9,
                season:"октябрь"
            },
              {name:"Атолл Раа",
          		visa:true,
                temperature:33,
                hotel:25860,
                tickets:10003,
                rating:10,
                season:"ноябрь"},

            ]},
            {
            name:"Филлипины",
            children:[
              {name:"Эль-Нидо",
          		visa:true,
                temperature:33,
                hotel:15600,
                tickets:7500,
                rating:8,
                season:"март"
            },
              {name:"Боракай",
          		visa:true,
                temperature:33,
                hotel:14590,
                tickets:6980,
                rating:9,
                season:"май"
            },
              {name:"Себу и Бохол",
          		visa:true,
                temperature:33,
                hotel:12560,
                tickets:3950,
                rating:6,
                season:"апрель"
            },

            ]},
            {
            name:"Шри-Ланка",
            children:[
              {name:"Тринкомале",
          		visa:true,
                temperature:25,
                hotel:16530,
                tickets:3256,
                rating:9,
                season:"январь"
            },
              {name:"Унаватуна",
          		visa:true,
                temperature:24,
                hotel:17250,
                tickets:5326,
                rating:6,
                season:"февраль"
            },
              {name:"Хиккадува",
          		visa:true,
                temperature:28,
                hotel:15990,
                tickets:5630,
                rating:7,
                season:"ноябрь"
            },
            ]},
            {
            name:"Куба",
            children:[
              {name:"Гавана",
          		visa:false,
                temperature:33,
                hotel:14860,
                tickets:5630,
                rating:7,
                season:"декабрь"
            },
              {name:"Варадеро",
          		visa:false,
                temperature:38,
                hotel:13830,
                tickets:5860,
                rating:6,
                season:"апрель"
            },

            ]},
            {
            name:"Доминикана",
            children:[
              {name:"Пунта Кана",
          		visa:false,
                temperature:25,
                hotel:10630,
                tickets:4731,
                rating:6,
                season:"апрель"
            },
              {name:"Бока-Чика",
          		visa:false,
                temperature:28,
                hotel:10900,
                tickets:4298,
                rating:7,
                season:"январь"
            },
              {name:"Ла Романа",
          		visa:false,
                temperature:30,
                hotel:11500,
                tickets:6523,
                rating:9,
                season:"март"
            },
              {name:"Санто-Доминго",
          		visa:false,
                temperature:31,
                hotel:13830,
                tickets:3952,
                rating:8,
                season:"ноябрь"
            },
              {name:"Кап Кана",
          		visa:false,
                temperature:22,
                hotel:13830,
                tickets:3862,
                rating:6,
                season:"декабрь"
            }
            ]},
            {
            name:"Гавайи",
            children:[
              {name:"Оаху",
          		visa:true,
                temperature:30,
                hotel:9860,
                tickets:3958,
                rating:5,
                season:"август"
            },
              {name:"Молокаи",
          		visa:true,
                temperature:31,
                hotel:8596,
                tickets:2536,
                rating:4,
                season:"август"
            },
            ]}
          ]},
          {
          name:"Европейские страны",
          children:[
            {
            name:"Испания",
            children:[
              {name:"Мадрид",
          		visa:true,
                temperature:30,
                hotel:10456,
                tickets:3596,
                rating:9,
                season:"август"
            },
              {name:"Барселона",
          		visa:true,
                temperature:28,
                hotel:12890,
                tickets:4258,
                rating:5,
                season:"июль"
            },
              {name:"Пальма",
          		visa:true,
                temperature:29,
                hotel:11528,
                tickets:3469,
                rating:7,
                season:"июнь"
            },
              {name:"Кордова",
          		visa:true,
                temperature:27,
                hotel:10783,
                tickets:4539,
                rating:8,
                season:"август"
            }
            ]},
            {
            name:"Португалия",
            children:[
              {name:"Абрантиш",
          		visa:true,
                temperature:23,
                hotel:15896,
                tickets:20536,
                rating:10,
                season:"октябрь"
            },
              {name:"Авейру",
          		visa:true,
                temperature:18,
                hotel:14732,
                tickets:19500,
                rating:8,
                season:"май"
            },
              {name:"Агуалва-Касен",
          		visa:true,
                temperature:20,
                hotel:17654,
                tickets:25893,
                rating:9,
                season:"июнь"
            },
              {name:"Вила-Нова-ди-Санту-Андре",
          		visa:true,
                temperature:16,
                hotel:13571,
                tickets:26473,
                rating:7,
                season:"июль"
            },
              {name:"Вила-Реал-ди-Санту-Антониу",
          		visa:true,
                temperature:24,
                hotel:16659,
                tickets:27962,
                rating:4,
                season:"август"
            },
              {name:"Каштелу-Бранку",
          		visa:true,
                temperature:20,
                hotel:16895,
                tickets:17856,
                rating:8,
                season:"сентябрь"
            }
            ]},
            {
            name:"Греция",
            children:[
              {name:"Афины",
          visa:true,
                temperature:25,
                hotel:19879,
                tickets:12369,
                rating:10,
                season:"апрель"
            },
              {name:"Салоники",
          		visa:true,
                temperature:29,
                hotel:19567,
                tickets:15000,
                rating:10,
                season:"сентябрь"
            },
              {name:"Ираклион",
          		visa:true,
                temperature:26,
                hotel:19888,
                tickets:18456,
                rating:9,
                season:"ноябрь"
            },

              {name:"Волос",
          		visa:true,
                temperature:36,
                hotel:20569,
                tickets:8563,
                rating:8,
                season:"июнь"
            },
              {name:"Ахарнес",
          		visa:true,
                temperature:40,
                hotel:21456,
                tickets:9365,
                rating:9,
                season:"июль"
            }
            ]},
            {
            name:"Черногория",
            children:[
              {name:"Подгорица",
          		visa:true,
                temperature:25,
                hotel:5320,
                tickets:2500,
                rating:7,
                season:"сентябрь"
            },
              {name:"Цетине",
          		visa:true,
                temperature:28,
                hotel:6890,
                tickets:895,
                rating:4,
                season:"май"
            },
              {name:"Андриевица",
          		visa:true,
                temperature:23,
                hotel:4328,
                tickets:900,
                rating:2,
                season:"август"
            },
              {name:"Бар",
          		visa:true,
                temperature:25,
                hotel:3500,
                tickets:1569,
                rating:3,
                season:"июнь"
            }
            ]},
            {
            name:"Италия",
            children:[
              {name:"Бар",
          		visa:true,
                temperature:18,
                hotel:14865,
                tickets:6905,
                rating:9,
                season:"март"
            },

              {name:"Милан",
          		visa:true,
                temperature:16,
                hotel:15900,
                tickets:7098,
                rating:9,
                season:"апрель"
            },

              {name:"Неаполь",
         		visa:true,
                temperature:15,
                hotel:14500,
                tickets:8094,
                rating:8,
                season:"март"
            },
              {name:"Турин",
          		visa:true,
                temperature:20,
                hotel:14000,
                tickets:5369,
                rating:7,
                season:"февраль"
            }
            ]},
            {
            name:"Франция",
            children:[
              {name:"Париж",
          visa:true,
                temperature:22,
                hotel:23568,
                tickets:19858,
                rating:10,
                season:"сентябрь"
            },
              {name:"Марсель",
          visa:true,
                temperature:18,
                hotel:25987,
                tickets:7896,
                rating:8,
                season:"октябрь"
            },
              {name:"Лион",
                visa:true,
                temperature:15,
                hotel:24111,
                tickets:6379,
                rating:9,
                season:"октябрь"
            },
              {name:"Страсбург",
          visa:true,
                temperature:17,
                hotel:26985,
                tickets:5239,
                rating:6,
                season:"сентябрь"
            }
            ]}
          ]}
    ]}
  ]
}